// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = {
    site: {
      admin: {
        name: "fucker",
        passwd: "123"
      },
      view: './view',
      db: {
        url: "mongodb://localhost/blog"
      }
    },
    view: {
      path: './server/templates/'
    },
    tpl_globals: {
      static_path: '/static/'
    }
  };

}).call(this);
